# ===== PROD（Render） =====
spring:
    config:
        activate:
            on-profile: prod

    datasource:
        url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require
        username: ${DB_USER}
        password: ${DB_PASSWORD}

    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                jdbc:
                    time_zone: UTC
                format_sql: false

    jackson:
        # 本番API/JSONもJSTで返す
        time_zone: Asia/Tokyo

    flyway: 
      enabled: true
      locations: classpath:db/migration
      baseline-on-migrate: true