spring:
    profiles:
        default: dev

---
# ===== DEV（ローカル） =====
spring:
    config:
        activate:
            on-profile: dev
    datasource:
        url: jdbc:postgresql://${DB_HOST:${LOCAL_DB_HOST:localhost}}:${DB_PORT:${LOCAL_DB_PORT:5432}}/${DB_NAME:${LOCAL_DB_NAME:life_calc}}
        username: ${DB_USER:${LOCAL_DB_USER:life_user}}
        password: ${DB_PASSWORD:${LOCAL_DB_PASSWORD:lifepass}}
        hikari:
            maximum-pool-size: 5
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                jdbc:
                    time_zone: Asia/Tokyo
                format_sql: true
    flyway:
        enabled: true
        locations: classpath:db/migration
        baseline-on-migrate: true

---
# ===== PROD（Render） =====
spring:
    config:
        activate:
            on-profile: prod
    datasource:
        url: jdbc:postgresql://${DB_HOST_PROD}:${DB_PORT_PROD}/${DB_NAME}?sslmode=require
        username: ${DB_USER}
        password: ${DB_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: validate
    flyway: 
      enabled: true
      locations: classpath:db/migration
      baseline-on-migrate: true