# ===== DEV（ローカル） =====
spring:
    config:
        activate:
            on-profile: dev
    datasource:
        url: jdbc:postgresql://${LOCAL_DB_HOST:localhost}:${LOCAL_DB_PORT:5432}/${LOCAL_DB_NAME:life_calc}
        username: ${LOCAL_DB_USER:life_user}
        password: ${LOCAL_DB_PASSWORD:lifepass}
        hikari:
            maximum-pool-size: 5
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                jdbc:
                    time_zone: UTC
                format_sql: true
    
    jackson:
        # API/JSON の時刻表示はJST
        time_zone: Asia/Tokyo

    flyway:
        enabled: true
        locations: classpath:db/migration
        baseline-on-migrate: true

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql.BasicBinder : warn