CREATE TABLE history_entry (
    id BIGINT generated by DEFAULT as identity PRIMARY KEY,
    user_id BIGINT NOT NULL DEFAULT 0,
    income BIGINT,
    fixed_cost_total BIGINT NOT NULL,
    result_variable BIGINT NOT NULL,
    saved_at TIMESTAMP not NULL DEFAULT now()
);

CREATE TABLE history_item (
    id BIGINT generated by DEFAULT as identity PRIMARY KEY,
    entry_id BIGINT NOT NULL,
    idx INT NOT NULL,
    amount BIGINT NOT NULL
);

ALTER TABLE history_item
    add constraint fk_history_item_entry
    Foreign Key (entry_id) REFERENCES history_entry(id) ON DELETE cascade;

CREATE INDEX idx_history_entry_saved_at on history_entry(saved_at DESC);
CREATE INDEX idx_history_item_entry on history_item(entry_id);