-- users/roles 基本
CREATE TABLE roles (
    id BIGINT generated by DEFAULT as identity PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    saved_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE app_user (
    id BIGINT generated by DEFAULT as identity PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    role_id BIGINT NOT NULL,
    saved_at TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE RESTRICT
);