-- users / roles / user_role（H2/PG両対応）

CREATE TABLE users (
    id          BIGINT generated by DEFAULT as identity PRIMARY KEY,
    username    VARCHAR(50) NOT NULL UNIQUE,
    email       VARCHAR(255),
    password    VARCHAR(100) NOT NULL,
    enabled     BOOLEAN NOT NULL DEFAULT true,
    saved_at    TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE roles (
    id      BIGINT generated by DEFAULT as identity PRIMARY KEY,
    name    VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE user_role (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id)
);

-- 参照制約（あと貼り）
ALTER TABLE user_role
    ADD constraint fk_user_role_user
    Foreign Key (user_id) REFERENCES roles(id) ON DELETE cascade;

ALTER TABLE user_role
    ADD constraint fk_user_role_role
    Foreign Key (role_id) REFERENCES roles(id) ON DELETE cascade;

-- 既存データ用のゲストユーザー（id=0）を用意
INSERT INTO users(id, username, email, password, enabled)
VALUES (0, 'guest', NULL , '!', false);

-- 役割の種
INSERT INTO roles(name) VALUES ('ROLE_USER'), ('ROLE_ADMIN');

-- history_entry.user_id を users(id) にひも付け（今は NOT NULL & default 0 なので整合OK）
ALTER TABLE history_entry
    ADD constraint fk_history_entry_user
    Foreign Key (user_id) REFERENCES users(id);