-- users/roles 基本
CREATE TABLE app_user (
    id BIGINT generated by DEFAULT as identity PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    saved_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE role (
    id BIGINT generated by DEFAULT as identity PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    saved_at TIMESTAMP NOT NULL DEFAULT now()
);

-- 多対多（ユーザーに複数ロール）
CREATE TABLE app_user_roles (
    user_id BIGINT NOT NULL REFERENCES app_user(id) on delete CASCADE,
    role_id BIGINT NOT NULL REFERENCES role(id) on delete RESTRICT,
    PRIMARY KEY (user_id, role_id)
);

-- デフォルトロール
INSERT INTO role(name) VALUES ('USER');